SocialNetwork/SocialNetwork/Models/PostViewModel.cs
using Microsoft.AspNetCore.Http;
using SocialNetwork.Data.Models;
using SocialNetwork.Data.Models.Enums;
using SocialNetwork.Web.Models.Users;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace SocialNetwork.Web.Models
{
    public class PostViewModel
    {
        public int Id { get; set; }
        public string Content { get; set; }

        [JsonIgnore]
        public AccessStatus AccessStatus { get; set; }

        [JsonIgnore]
        public int? PhotoId { get; set; }
        public string PhotoName { get; set; }
        public string VideoUrl { get; set; }
        public string Username { get; set; }

        [JsonIgnore]
        public UserViewModel User { get; set; }

        [JsonIgnore]
        public Guid UserId { get; set; }

        [NotMapped]
        [JsonIgnore]
        public IFormFile PhotoFile { get; set; }

        [NotMapped]
        [JsonIgnore]
        public int Count { get; set; }

        [JsonIgnore]
        public int CommentsCount { get; set; }

        [JsonIgnore]
        public virtual ICollection<CommentViewModel> Comments { get; set; }

        [JsonIgnore]
        public virtual ICollection<LikeViewModel> Likes { get; set; }
        public DateTime CreatedOn { get; set; }
        //public bool IsDeleted { get; set; }
        //public DateTime? DeletedOn { get; set; }
    }
}

SocialNetwork/SocialNetwork/Models/Users/FriendsViewModel.cs
namespace SocialNetwork.Web.Models.Users
{
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public class FriendsViewModel
    {
        public IEnumerable<UserViewModel> Friends { get; set; }

        [JsonIgnore]
        public int CurrentPage { get; set; }
        [JsonIgnore]
        public int FriendsPagesCount { get; set; }
    }
}

SocialNetwork/SocialNetwork/Models/Users/UserInputViewModel.cs
namespace SocialNetwork.Web.Models.Users
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.AspNetCore.Http;

    public class UserInputViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "First name is required.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email address is required.")]
        [EmailAddress]
        public string Email { get; set; }
        [StringLength(375, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]
        public string Bio { get; set; }
        [StringLength(375, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]
        public string JobTitle { get; set; }
        public bool IsPrivate { get; set; }
        public string PhotoName { get; set; }
        public string Country { get; set; }
        public DateTime DateOfBirth { get; set; }
        public IFormFile PhotoFile { get; set; }
        public string DateOfBirthView => DateOfBirth.ToShortDateString();

        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$", ErrorMessage = "Password must be at least 6 characters and should contain at least 1 letter and 1 number")]
        public string CurrentPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$", ErrorMessage = "Password must be at least 6 characters and should contain at least 1 letter and 1 number")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("NewPassword", ErrorMessage = "The passwords does not match.")]
        public string RepeatNewPassword { get; set; }
    }
}

SocialNetwork/SocialNetwork/Models/Users/UserPhotosViewModel.cs
namespace SocialNetwork.Web.Models.Users
{
    using System;
    using System.Collections.Generic;

    public class UserPhotosViewModel
    {
        public Guid Id { get; set; }
        public IEnumerable<string> Photos { get; set; }
    }
}

SocialNetwork/SocialNetwork/Models/Users/UserPostsViewModel.cs
namespace SocialNetwork.Web.Models.Users
{
    using System.Collections.Generic;

    public class UserPostsViewModel
    {
        public IEnumerable<PostViewModel> Posts { get; set; }
        public int CurrentPage { get; set; }
        public int PostsPagesCount { get; set; }
    }
}

SocialNetwork/SocialNetwork/Models/Users/UserSearchViewModel.cs
namespace SocialNetwork.Web.Models.Users
{
    using System.Collections.Generic;

    public class UserSearchViewModel
    {
        public IEnumerable<UserViewModel> Users { get; set; }
        public int CurrentPage { get; set; }
        public int UsersPagesCount { get; set; }
        public int TotalUsers { get; set; }
        public string SearchParameter { get; set; }
    }
}

SocialNetwork/SocialNetwork/Models/Users/UserViewModel.cs
namespace SocialNetwork.Web.Models.Users
{
    using Microsoft.AspNetCore.Http;
    using SocialNetwork.Web.Models;
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text.Json.Serialization;

    public class UserViewModel
    {
        public Guid Id { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhotoName { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string JobTitle { get; set; }
        public bool IsPrivate { get; set; }
        public string Bio { get; set; }
        [JsonIgnore]
        public PhotoViewModel ProfilePicture { get; set; }
        [JsonIgnore]
        public IFormFile PhotoFile { get; set; }
        [JsonIgnore]
        public ICollection<PostViewModel> Posts { get; set; }
        public string FullName => $"{this.FirstName} {this.LastName}";
        [JsonIgnore]
        public IEnumerable<UserViewModel> Friends { get; set; }
        public int FriendsCount { get; set; }
        public int Age => (DateTime.Today.Year - DateOfBirth.Year);
        [JsonIgnore]
        public DateTime CreatedOn { get; set; }
        [JsonIgnore]
        public string CreatedDate => $"{this.CreatedOn.Day} {this.CreatedOn.ToString("MMM", CultureInfo.InvariantCulture)} {this.CreatedOn.Year}";
        [JsonIgnore]
        public bool AreFriends { get; set; }
        [JsonIgnore]
        public bool IsRequestSent { get; set; }
    }
}

SocialNetwork/SocialNetwork/Controllers/UsersController.cs
namespace SocialNetwork.Web.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using SocialNetwork.Data.Models;
    using SocialNetwork.Services.EntityDTOs;
    using SocialNetwork.Services.PhotoService;
    using SocialNetwork.Services.UserFriend;
    using SocialNetwork.Services.UserService;
    using SocialNetwork.Web.CountriesGenerator;
    using SocialNetwork.Web.Models;
    using SocialNetwork.Web.Models.Users;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;


    public class UsersController : Controller
    {
        private const int FriendsPerPage = 4;
        private const int PostsPerPage = 5;
        private const int UsersPerPage = 5;

        private readonly IUserService userService;
        private readonly IUserFriendService userFriendService;
        private readonly IWebHostEnvironment environment;
        private readonly IPhotoService photoService;
        private readonly UserManager<User> userManager;
        private readonly IMapper mapper;

        public UsersController(IUserService userService, IMapper mapper, UserManager<User> userManager, IUserFriendService userFriendService,
             IWebHostEnvironment environment, IPhotoService photoService)
        {
            this.userService = userService;
            this.environment = environment;
            this.photoService = photoService;
            this.userFriendService = userFriendService;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid userId);

            if (result == false)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            var user = await this.userService.GetUser(userId);

            var userToViewModel = this.mapper.Map<UserViewModel>(user);

            return View(userToViewModel);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("users/{id:Guid}")]
        public async Task<IActionResult> Index(Guid id)
        {
            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid visitorUserId);

            if (id == visitorUserId)
            {
                return Redirect("https://localhost:5001/users");
            }

            var user = await this.userService.GetUser(id);

            var userToViewModel = this.mapper.Map<UserViewModel>(user);

            if (result)
            {
                if (id != visitorUserId)
                {
                    var areFriends = await this.userService.CheckIfFriends(id, visitorUserId);

                    if (areFriends)
                    {
                        userToViewModel.AreFriends = true;
                    }
                    else
                    {
                        var isRequestSent = await this.userService.CheckIfRequestIsSent(id, visitorUserId);

                        if (isRequestSent)
                        {
                            userToViewModel.IsRequestSent = true;
                        }
                    }
                }
            }

            return View(userToViewModel);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("users/getuserposts/{id:Guid}")]
        public async Task<IActionResult> GetUserPosts(Guid id, int page = 1)
        {
            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid visitorId);

            IEnumerable<PostDTO> userPosts = await this.userService.GetAllUserPosts(id, visitorId, PostsPerPage, (page - 1) * PostsPerPage);

            var count = await this.userService.GetPostsCount(id, visitorId);

            var userPostsInViewModel = new UserPostsViewModel
            {
                Posts = userPosts.Select(p => this.mapper.Map<PostViewModel>(p)),
                PostsPagesCount = (int)Math.Ceiling((double)count / PostsPerPage)
            };

            if (userPostsInViewModel.PostsPagesCount == 0)
            {
                userPostsInViewModel.PostsPagesCount = 1;
            }

            userPostsInViewModel.CurrentPage = page;

            return PartialView("Posts", userPostsInViewModel);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpGet("users/getuserfriends/{id:Guid?}")]
        public async Task<IActionResult> GetUserFriends(Guid id, int page = 1)
        {
            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid visitorId);

            IEnumerable<UserDTO> userFriends;

            if (result)
            {
                userFriends = await this.userService.GetAllFriendsWithVisitor(id, visitorId, FriendsPerPage, (page - 1) * FriendsPerPage);
            }
            else
            {
                userFriends = await this.userService.GetAllFriends(id, FriendsPerPage, (page - 1) * FriendsPerPage);
            }

            var count = this.userService.GetFriendsCount(id, visitorId);

            var userFriendsInViewModel = new FriendsViewModel
            {
                Friends = userFriends.Select(u => this.mapper.Map<UserViewModel>(u)),
                FriendsPagesCount = (int)Math.Ceiling((double)count / FriendsPerPage)
            };

            if (userFriendsInViewModel.FriendsPagesCount == 0)
            {
                userFriendsInViewModel.FriendsPagesCount = 1;
            }

            userFriendsInViewModel.CurrentPage = page;

            return PartialView("_SingleFriendPartial", userFriendsInViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFriend(Guid id)
        {
            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid userId);

            if (result == false)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            var removeFriend = await this.userFriendService.RemoveFriend(userId, id);

            if (removeFriend == false)
            {
                return BadRequest();
            }

            return Content("Friend Removed");
        }

        public async Task<IActionResult> Search(string searchParameter = null, int page = 1)
        {
            var users = await this.userService.GetAllUsers(searchParameter, UsersPerPage, (page - 1) * UsersPerPage);

            int usersCount;

            if (searchParameter != null)
            {
                usersCount = this.userService.GetUsersCountWithSearchParameter(searchParameter);
            }
            else
            {
                usersCount = this.userService.GetUsersCount();
            }

            var userSearchViewModel = new UserSearchViewModel
            {
                Users = users.Select(u => this.mapper.Map<UserViewModel>(u)),
                UsersPagesCount = (int)Math.Ceiling((double)usersCount / UsersPerPage),
                TotalUsers = usersCount,
            };

            if (searchParameter != null)
            {
                userSearchViewModel.SearchParameter = searchParameter;
            }

            if (userSearchViewModel.UsersPagesCount == 0)
            {
                userSearchViewModel.UsersPagesCount = 1;
            }

            userSearchViewModel.CurrentPage = page;

            return View(userSearchViewModel);
        }

        public async Task<IActionResult> GetUserPhotos(Guid id)
        {
            var user = await this.userService.GetUser(id);

            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid visitorId);

            bool showPictures;

            if (user.IsPrivate)
            {
                if (visitorId == id)
                {
                    showPictures = true;
                }
                else if (await this.userService.CheckIfFriends(id, visitorId))
                {
                    showPictures = true;
                }
                else
                {
                    showPictures = false;
                }
            }
            else
            {
                showPictures = true;
            }

            UserPhotosViewModel userPhotos = new UserPhotosViewModel
            {
                Id = id
            };

            if (showPictures)
            {
                string idToString = id.ToString();

                var rootDir = $"{this.environment.WebRootPath}/images/{idToString}";

                var img = Directory.EnumerateFiles(rootDir)
                    .Select(a => Path.GetRelativePath(rootDir, a))
                    .Select(a => a.Replace("\\", "/"));

                userPhotos.Photos = img;
            }
            else
            {
                userPhotos.Photos = Enumerable.Empty<string>();
            }

            return PartialView("_SinglePhotoPartial", userPhotos);
        }

        public async Task<IActionResult> GetUserLatestPhotos(Guid id)
        {
            var user = await this.userService.GetUser(id);

            var result = Guid.TryParse(this.userManager.GetUserId(this.User), out Guid visitorId);

            bool showPictures;

            if (user.IsPrivate)
            {
                if (visitorId == id)
                {
                    showPictures = true;
                }
                else if (await this.userService.CheckIfFriends(id, visitorId))
                {
                    showPictures = true;
                }
                else
                {
                    showPictures = false;
                }
            }
            else
            {

SocialNetwork/SocialNetwork/Views/Users/Edit.cshtml
@model SocialNetwork.Web.Models.Users.UserInputViewModel

@section Styles {
    <link rel="stylesheet" href="~/css/UserEdit.css" />
    <link rel="stylesheet" href="~/css/foopicker.css" />
}

@{ 
    string photo;

    if (Model.PhotoName == null)
    {
        photo = "profilePicture.png";
    }
    else
    {
        photo = $"{Model.Id}/{Model.PhotoName}";
    }
}

<script type="text/javascript" src="~/js/foopicker.js"></script>

<div class="container light-style flex-grow-1 container-p-y">

    <h4 class="font-weight-bold py-3 mb-4">
        Account settings
    </h4>

    <div class="card overflow-hidden">
        <div class="row no-gutters row-bordered row-border-light">
            <div class="col-md-3 pt-0">
                <div class="list-group list-group-flush account-settings-links">
                    <a class="list-group-item list-group-item-action active" data-toggle="list" href="#account-general">General</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-info">Info</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list" href="#account-change-password">Change password</a>
                </div>
            </div>
            <div class="col-md-9">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">
                            <div class="card-body media align-items-center">
                                <img src="@Url.Content($"~/images/{photo}")" alt="" class="d-block ui-w-80">
                                <div class="media-body ml-4">
                                    <label class="btn btn-outline-primary">
                                        Upload new photo
                                        <input asp-for="PhotoFile" class="account-settings-fileinput" accept="image/*">
                                    </label> &nbsp;

                                    <div class="text-light small mt-1">Allowed JPG and PNG.</div>
                                </div>
                            </div>
                            <hr class="border-light m-0">

                            <div class="card-body">
                                <div class="form-group">
                                    <label class="form-label">First Name</label>
                                    <input asp-for="FirstName" type="text" class="form-control mb-1" value="@Model.FirstName">
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Last Name</label>
                                    <input asp-for="LastName" type="text" class="form-control" value="@Model.LastName">
                                    <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">E-mail</label>
                                    <input asp-for="Email" type="text" class="form-control mb-1" value="@Model.Email">
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Birthday</label>
                                    <input class="form-control" type="text" id="datepicker" asp-for="DateOfBirth" value="@Model.DateOfBirthView" />
                                </div>
                                <h5 class="mb-4">Profile Privacy</h5>
                                <div class="form-group">
                                    <label class="switcher">
                                        <input type="checkbox" value="true" name="IsPrivate" checked="@Model.IsPrivate" />
                                        <span class="switcher-label">Private Profile</span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-info">
                            <div class="card-body pb-2">

                                <div class="form-group">
                                    <label class="form-label">Bio</label>
                                    <textarea asp-for="Bio" value="@Model.Bio" class="form-control" rows="5"></textarea>
                                    <span asp-validation-for="Bio" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Job Title</label>
                                    <input asp-for="JobTitle" type="text" class="form-control" value="@Model.JobTitle">
                                    <span asp-validation-for="JobTitle" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Country</label>
                                    <select asp-for="Country" class="form-control" asp-items="ViewBag.Countries"></select>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-change-password">
                            <div class="card-body pb-2">

                                <div class="form-group">
                                    <label class="form-label">Current password</label>
                                    <input asp-for="CurrentPassword" type="password" class="form-control">
                                    <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label class="form-label">New password</label>
                                    <input asp-for="NewPassword" type="password" class="form-control">
                                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label class="form-label">Repeat new password</label>
                                    <input asp-for="RepeatNewPassword" type="password" class="form-control">
                                    <span asp-validation-for="RepeatNewPassword" class="text-danger"></span>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right mr-5">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@*<div class="text-right mt-3">
        <button type="button" class="btn btn-primary">Save changes</button>&nbsp;
        <button type="button" class="btn btn-default">Cancel</button>
    </div>*@

<script type="text/javascript">
    var foopicker = new FooPicker({
        id: 'datepicker',
        dateFormat: 'MM/dd/yyyy'
    });
</script>

SocialNetwork/SocialNetwork/Views/Users/Search.cshtml
@model SocialNetwork.Web.Models.Users.UserSearchViewModel

@section Styles {
    <link rel="stylesheet" href="~/css/Search.css" />
}

<form asp-controller="Users" asp-action="Search" method="get">
    <div class="row justify-content-center">
        <div class="col-8 p-1 bg-light rounded rounded-pill shadow-sm mb-4">
            <div class="input-group">
                <input type="search" name="searchParameter" placeholder="Search User" aria-describedby="button-addon2" class="form-control border-0 bg-light">
                <div class="input-group-prepend">
                    <button id="button-addon2" type="submit" class="btn btn-link text-warning"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="container mb-3">
    <div class="row ng-scope">
        <div class="col-md-11 col-md-pull-3">
            <p class="search-results-count">About @Model.TotalUsers results</p>
            @foreach (var item in Model.Users)
            {
                <section class="search-result-item">
                    <a class="image-link" href="#">
                        @if (item.IsPrivate)
                        {
                            <img class="image" src="@Url.Content($"~/images/profilePicture.png")">
                        }
                        else
                        {
                            if (item.PhotoName == null)
                            {
                                <img class="image" src="@Url.Content($"~/images/profilePicture.png")">
                            }
                            else
                            {
                                <img class="image" src="@Url.Content($"~/images/{item.Id}/{item.PhotoName}")">
                            }
                        }
                    </a>
                    <div class="search-result-item-body">
                        <div class="row align-items-center">
                            <div class="col-sm-9">
                                <h4 class="search-result-item-heading"><a href="#">@item.FullName</a></h4>
                                <p class="info">@item.Country</p>
                                <p class="description">@item.Bio</p>
                            </div>
                            <div class="col-sm-3 text-align-center">
                                <a asp-controller="Users" asp-action="Index" asp-route-id="@item.Id" class="btn btn-primary btn-info btn-sm">Go To Profile</a>
                            </div>
                        </div>
                    </div>
                </section>
            }
        </div>
    </div>
</div>

<nav>
    <ul class="pagination pagination-lg justify-content-center">
        @for (int i = 1; i <= this.Model.UsersPagesCount; i++)
        {
            var active = i == this.Model.CurrentPage ? "active" : string.Empty;
            <li class="page-item @active">
                <a class="page-link" style="padding: .5rem 1rem" asp-action="Search" asp-route-searchParameter="@Model.SearchParameter" asp-route-page="@i">@i</a>
            </li>
        }
    </ul>
</nav>